volumes:
  postgres_data:
    driver: local

services:
  api:
    container_name: backend
    build: 
      context: ./api
    ports:
      - "8000:8000"
    networks:
      - admin-js
  client:
    build: 
      context: ./client
    ports:
      - "8800:80"
    networks:
      - admin-js
networks:
  admin-js:
    driver: bridge